import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["src/**/*.test.ts", "src/**/*.spec.ts"],
    setupFiles: ["./src/__tests__/setup.ts"],
    env: {
      NODE_ENV: "test",
      PORT: "4000",
      LOG_LEVEL: "error",
      CLIENT_URL: "http://localhost:5173",
      DATABASE_URL: process.env.DATABASE_URL ?? "postgresql://urs_user:urs_password@localhost:5432/urs_dms?schema=public",
      JWT_ACCESS_SECRET: "test-jwt-access-secret-at-least-32-chars-long-for-vitest",
      JWT_ACCESS_EXPIRES_IN: "15m",
      JWT_REFRESH_SECRET: "test-jwt-refresh-secret-at-least-32-chars-long-for-vitest",
      JWT_REFRESH_EXPIRES_IN: "7d",
      JWT_ISSUER: "urs-dms-test",
      JWT_AUDIENCE: "urs-dms-client-test",
      COOKIE_DOMAIN: "localhost",
      COOKIE_SECURE: "false",
      COOKIE_SAME_SITE: "lax",
      MINIO_ENDPOINT: "localhost",
      MINIO_PORT: "9000",
      MINIO_USE_SSL: "false",
      MINIO_ACCESS_KEY: "urs_minio_admin",
      MINIO_SECRET_KEY: "urs_minio_secret",
      MINIO_BUCKET: "urs-dms",
      RATE_LIMIT_WINDOW_MS: "900000",
      RATE_LIMIT_MAX: "100",
      MAX_FAILED_LOGIN_ATTEMPTS: "5",
      LOCK_DURATION_MIN: "15",
      PASSWORD_MIN_LENGTH: "8",
      SESSION_REFRESH_ROTATION: "true",
      TRUST_PROXY: "1",
      EMAIL_PROVIDER: "console",
      REDIS_HOST: "localhost",
      REDIS_PORT: "6379",
      WORKER_CONCURRENCY: "1",
      JOB_RETRY_LIMIT: "1",
      JOB_TIMEOUT_MS: "30000",
      ZIP_EXPIRATION_SECONDS: "300",
    },
    coverage: {
      provider: "v8",
      include: ["src/modules/**/*.ts"],
      exclude: [
        "src/modules/**/*.validator.ts",
        "src/modules/**/*.types.ts",
        "src/modules/**/*.controller.ts",
        "src/modules/**/*.routes.ts",
        "src/**/__tests__/**",
        "src/config/**",
        "src/utils/logger.ts",
      ],
    },
    testTimeout: 15_000,
    hookTimeout: 10_000,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
});
